---
- name: clone cosmos-faucet repo
  git:
    repo: https://github.com/allinbits/cosmos-faucet.git
    dest: /usr/local/src/faucet
    version: "{{ faucet_version }}"

- name: build cosmos-faucet
  args:
    chdir: /usr/local/src/faucet
    executable: /bin/bash
  shell: go build ./cmd/faucet && mv faucet /usr/local/bin/faucet

- name: install cosmos-faucet service
  template:
    src: templates/faucet.service.j2
    dest: /etc/systemd/system/faucet.service
    owner: root
    group: root
    mode: 0644

- name: start the cosmos-faucet service
  systemd:
    name: faucet
    daemon_reload: yes
    state: restarted
    enabled: True
